name: Python Linting
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          flake8 code --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 code --count --max-complexity=10 --max-line-length=999 --statistics
      # - name: Lint with Pylint
      #   run: |
      #     pylint opdracht1/code